# Generated by Django 2.0.6 on 2020-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
