# Generated by Django 2.0.6 on 2020-04-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200412_2234'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='t_article',
        ),
    ]
