# Generated by Django 2.0.6 on 2020-04-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('picture_title', models.CharField(max_length=200)),
                ('picture_status', models.BooleanField()),
                ('picture_url', models.ImageField(null=True, upload_to='pictures')),
            ],
        ),
    ]
